services:
    gsquad_blog.image_type_extension:
        class: Gsquad\BlogBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }

    gsquad_blog.slugger:
        class: Gsquad\BlogBundle\Utils\Slugger