gsquad_blog:
    resource: "@GsquadBlogBundle/Controller/"
    type:     annotation
    prefix:   /blog

app:
    resource: "@GsquadCoreBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
