gsquad_blog:
    resource: "@GsquadBlogBundle/Controller/"
    type:     annotation
    prefix:   /blog

app:
    resource: "@GsquadCoreBundle/Controller/"
    type:     annotation
    prefix:   /

app_search:
    resource: "@GsquadPiafBundle/Controller"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /login

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login



facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

mentions_legales:
    path: /mentions-legales
    defaults:
        _controller: FrameworkBundle:Template:template
        template: static/mentions_legales.html.twig

conditions_generales:
    path: /conditions-generales
    defaults:
        _controller: FrameworkBundle:Template:template
        template: static/conditions_generales.html.twig

faq:
    path: /faq
    defaults:
        _controller: FrameworkBundle:Template:template
        template: static/faq.html.twig

about:
    path: /a-propos
    defaults:
        _controller: FrameworkBundle:Template:template
        template: static/about.html.twig

adhesion:
    path: /adhesion
    defaults:
        _controller: FrameworkBundle:Template:template
        template: static/adhesion.html.twig
