# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_SUPER_ADMIN:       [ROLE_CHERCHEUR, ROLE_ADMIN]
        ROLE_CHERCHEUR:         ROLE_ADHERENT
        ROLE_ADHERENT:          ROLE_MEMBRE
        ROLE_ADMIN:             ROLE_REDACTEUR
        ROLE_REDACTEUR:         ROLE_CONTRIBUTEUR
        ROLE_CONTRIBUTEUR:      ROLE_UTILISATEUR


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                login_path:        /login
                failure_path:      /login

                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: gsquad.user_provider
            logout:       true
            anonymous:    true

        login:
            pattern:  ^/login$
            security: false



    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN }




