# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    gsquad.oauth.user_provider.class: Gsquad\UserBundle\OAuth\UserProvider

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    gsquad.oauth.user_provider:
        class: "%gsquad.oauth.user_provider.class%"
        arguments: ["@fos_user.user_manager", {facebook: facebook_id, google: google_id}]

    gsquad.slugger:
        class: Gsquad\Utils\Slugger

    gsquad.mailer:
        class: Gsquad\Utils\Mailer
        arguments: ["@mailer", "@templating"]

    gsquad.form.type.post:
        class: Gsquad\BlogBundle\Form\Type\PostType
        arguments: ["@doctrine.orm.entity_manager", "@gsquad.slugger"]
        tags:
            - { name: form.type }

    gsquad.password_generator:
        class: Gsquad\Utils\PasswordGenerator

    gsquad.users.roles_set:
        class: Gsquad\UserBundle\EventListener\NewUserRolesSet
        arguments: ["@fos_user.user_manager", "@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }

    gsquad.aws_s3.client:
        class: Aws\S3\S3Client
        arguments:
            -
                credentials:
                    key: '%amazon_s3.key%'
                    secret: '%amazon_s3.secret%'
                region: '%amazon_s3.region%'
                version: 'latest'
