# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    my_user_provider.class: Gsquad\UserBundle\Security\Core\User\FOSUBUserProvider

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    gsquad.user_provider:
            class: "%my_user_provider.class%"
            #this is the place where the properties are passed to the UserProvider - see config.yml
            arguments: ["@fos_user.user_manager",{facebook: facebook_id, google: google_id}]

    gsquad.slugger:
        class: Gsquad\Utils\Slugger

    gsquad.mailer:
        class: Gsquad\Utils\Mailer
        arguments: ["@mailer", "@templating"]

    gsquad.password_generator:
        class: Gsquad\Utils\PasswordGenerator
