services:
    gsquad_piaf.get_departements:
        class: Gsquad\PiafBundle\Service\GsquadGetDepartements

    gsquad_piaf.set_habitat:
        class: Gsquad\PiafBundle\Service\GsquadSetHabitat

    gsquad_piaf.modifier_coordonnees:
        class: Gsquad\PiafBundle\Service\GsquadChangeCoordinates

    gsquad_piaf.get_list_piafs:
        class: Gsquad\PiafBundle\Service\GsquadGetListPiaf