<?php

namespace Gsquad\BlogBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategoriesWithPosts()
    {
        $query = $this->createQueryBuilder('c');

        $query->select('c')
            ->innerJoin('c.posts', 'p')
                ->where('p.status = :status')
                ->setParameter('status', 'publié')
        ;

        return $query->getQuery()->getResult();
    }
}
