<?php

namespace Gsquad\BlogBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getNewComments($date)
    {
        $query = $this->createQueryBuilder('c');

        $query
            ->select('c')
            ->where('c.creationDate > :date')
            ->setParameter('date', $date)
        ;

        return $query
            ->getQuery()
            ->getResult();
    }
}
