<?php

namespace Gsquad\BlogBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getLastCommentWithPost($post)
    {
        dump($post);
        $qb = $this->createQueryBuilder('c')
            ->orderBy('c.creationDate', 'DESC')
            ->setMaxResults(1)
        ;

        // Puis on ne retourne que $limit résultats
        //$qb->setMaxResults($limit);

        // Enfin, on retourne le résultat
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
