<?php

namespace Gsquad\PiafBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findObservationByPosition($latitude, $longitude, $range) {
        $latMin = $latitude - $range;
        $latMax = $latitude + $range;
        $lonMin = $longitude - $range;
        $lonMax = $longitude + $range;

        $query = $this->createQueryBuilder('o')
            ->where('o.latitude >= :latmin')
            ->andWhere('o.latitude <= :latmax')
            ->andWhere('o.longitude >= :lonmin')
            ->andWhere('o.longitude <= :lonmax')
            ->setParameter('latmin', $latMin)
            ->setParameter('latmax', $latMax)
            ->setParameter('lonmin', $lonMin)
            ->setParameter('lonmax', $lonMax)
            ->getQuery();

        return $query->getResult();
    }
}
