<?php

namespace Gsquad\PiafBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PiafRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiafRepository extends EntityRepository
{
    public function fetchAllNomVern(){
        $query = $this
                    ->createQueryBuilder('v')
                    ->select('v.nameVern')
                    ->orderBy('v.nameVern', 'ASC')
                    ->getQuery()
        ;

        return $query->getResult();
    }

    public function fetchAllNomVernLbNom(){
        $query = $this
            ->createQueryBuilder('p')
            ->select('p.nameVern', 'p.lbNom')
            ->getQuery()
        ;

        return $query->getResult();
    }
}
