<?php

namespace Gsquad\PiafBundle\Repository;

/**
 * PiafRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiafRepository extends \Doctrine\ORM\EntityRepository
{
}
